# Generated by Django 3.0.3 on 2020-07-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothessite', '0002_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Signupmodel',
        ),
    ]
