# Generated by Django 3.0.3 on 2020-07-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothessite', '0003_auto_20200731_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signupmodel',
        ),
    ]
